In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import json
from datetime import datetime

In [35]:
# Carrega template de metadados

with open("metadata_schema.json", "r") as f:
    template = json.load(f)

print(template)

{'arquivo': '', 'descricao': '', 'formato': '', 'delimitador': '', 'codificacao': '', 'quantidade_linhas': '', 'colunas': [{'nome': '', 'tipo': '', 'descricao': ''}], 'fonte': '', 'data_coleta': 'YYYY-MM-DD', 'responsavel': '', 'observacoes': ''}

In [36]:
historico = pd.read_parquet("1-bronze/world_olympedia_olympics_game_medal_tally.parquet")
historico.head()

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total
0,1896,1896 Summer Olympics,1,Greece,GRE,10,18,19,47
1,1900,1900 Summer Olympics,2,France,FRA,31,41,40,112
2,1900,1900 Summer Olympics,2,United States,USA,20,13,15,48
3,1904,1904 Summer Olympics,3,United States,USA,80,85,83,248
4,1908,1908 Summer Olympics,5,Great Britain,GBR,56,51,39,146

In [53]:
# Gera os metadados do world_olympedia_olympics_game_medal_tally.parquet

historico_metadata = {
  "arquivo": "world_olympedia_olympics_game_medal_tally.parquet",
  "descricao": "Medalhas por país por edição de jogos olímpicos",
  "formato": "parquet",
  "delimitador": "",
  "codificacao": "UTF-8",
  "quantidade_linhas": "",
  "colunas": [
    {
      "nome": "year",
      "tipo": "Integer",
      "descricao": "Ano do evento"
    },
    {
      "nome": "edition",
      "tipo": "String",
      "descricao": "Edição dos jogos olímpicos"
    },
    {
      "nome": "edition_id",
      "tipo": "Integer",
      "descricao": "Identificação da edição"
    },
    {
      "nome": "country",
      "tipo": "String",
      "descricao": "Nome completo do país"
    },
    {
      "nome": "country_noc",
      "tipo": "String",
      "descricao": "Código único do país"
    },
    {
      "nome": "gold",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro obtidas"
    },
    {
      "nome": "silver",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata obtidas"
    },
    {
      "nome": "bronze",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze obtidas"
    },
    {
      "nome": "total",
      "tipo": "Integer",
      "descricao": "Número de total de medalhas obtidas"
    },
  ],
  "fonte": "raw/world_olympedia_olympics_game_medal_tally.csv",
  "data_coleta": datetime.now().isoformat(),
  "responsavel": "Matheus Nielsen",
  "observacoes": ""
}

with open("1-bronze/world_olympedia_olympics_game_medal_tally.meta.json", "w") as f:
    json.dump(historico_metadata, f)

In [37]:
# Ler e processar os dados das olimpiadas de verão de paris de 2024
paris = pd.read_parquet("1-bronze/medals_total.parquet")
paris = paris.rename(columns={
    "country_code":"country_noc",
    "Gold Medal":"gold",
    "Silver Medal" : "silver",
    "Bronze Medal" : "bronze",
    "Total": "total"
})
paris["year"] = 2024
paris["edition"] = "2024 Summer Olympics"
paris["edition_id"] = 999 # id ficticio


paris.head()

,country_noc,country,country_long,gold,silver,bronze,total,year,edition,edition_id
0,USA,United States,United States of America,40,44,42,126,2024,2024 Summer Olympics,999
1,CHN,China,People's Republic of China,40,27,24,91,2024,2024 Summer Olympics,999
2,JPN,Japan,Japan,20,12,13,45,2024,2024 Summer Olympics,999
3,AUS,Australia,Australia,18,19,16,53,2024,2024 Summer Olympics,999
4,FRA,France,France,16,26,22,64,2024,2024 Summer Olympics,999

In [ ]:
# Gera os metadados do medals_total.parquet

paris_metadata = {
  "arquivo": "medals_total.parquet",
  "descricao": "Medalhas por país dos jogos olimpicos de verao de paris 2024",
  "formato": "parquet",
  "delimitador": "",
  "codificacao": "",
  "quantidade_linhas": "",
  "colunas": [
    {
      "nome": "country_code",
      "tipo": "String",
      "descricao": "Código do país"
    },
    {
      "nome": "country",
      "tipo": "String",
      "descricao": "Nome do país"
    },
    {
      "nome": "country_long",
      "tipo": "String",
      "descricao": "Nome completo do país"
    },
    {
      "nome": "Gold Medal",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro obtidas"
    },
    {
      "nome": "Silver Medal",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata obtidas"
    },
    {
      "nome": "Bronze Medal",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze obtidas"
    },
    {
      "nome": "Total",
      "tipo": "Integer",
      "descricao": "Número de total de medalhas obtidas"
    },
  ],
  "fonte": "0-raw/medals_total.csv",
  "data_coleta": datetime.now().isoformat(),
  "responsavel": "Matheus Nielsen",
  "obeservacoes": ""
}

with open("1-bronze/medals_total.meta.json", "w") as f:
    json.dump(historico_metadata, f)

In [38]:
# Concatenar paris com o histórico
olimpiadas = pd.concat([historico, paris])
olimpiadas.tail()

,year,edition,edition_id,country,country_noc,gold,silver,bronze,total,country_long
87,2024,2024 Summer Olympics,999,Peru,PER,0,0,1,1,Peru
88,2024,2024 Summer Olympics,999,Qatar,QAT,0,0,1,1,Qatar
89,2024,2024 Summer Olympics,999,Singapore,SGP,0,0,1,1,Singapore
90,2024,2024 Summer Olympics,999,Slovakia,SVK,0,0,1,1,Slovakia
91,2024,2024 Summer Olympics,999,Zambia,ZAM,0,0,1,1,Zambia

In [39]:
# Salva o dataset combinado como parquet

olimpiadas.to_parquet("1-bronze/combined_olympics_medals.parquet")

olimpiadas_metadata = template.copy()

olimpiadas_metadata["arquivo"] = "combined_olympics_medals.parquet"
olimpiadas_metadata["descricao"] = "dataset combinado com os dados de world_olympedia_olympics_game_medal_tally e as medalhas das olimpiadas de verao de paris 2024"
olimpiadas_metadata["formato"] = "parquet"
olimpiadas_metadata["data_coleta"] = datetime.now().isoformat()
olimpiadas_metadata["responsavel"] = "Matheus Nielsen"
olimpiadas_metadata["colunas"] = [{
      "nome": "year",
      "tipo": "Integer",
      "descricao": "Ano do evento"
    },
    {
      "nome": "edition",
      "tipo": "String",
      "descricao": "Edição dos jogos olímpicos"
    },
    {
      "nome": "edition_id",
      "tipo": "Integer",
      "descricao": "Identificação da edição"
    },
    {
      "nome": "country",
      "tipo": "String",
      "descricao": "Nome completo do país"
    },
    {
      "nome": "country_noc",
      "tipo": "String",
      "descricao": "Código único do país"
    },
    {
      "nome": "gold",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro obtidas"
    },
    {
      "nome": "silver",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata obtidas"
    },
    {
      "nome": "bronze",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze obtidas"
    },
    {
      "nome": "total",
      "tipo": "Integer",
      "descricao": "Número de total de medalhas obtidas"
    },
]

with open("1-bronze/combined_olympics_medals.meta.json", "w") as f:
    json.dump(olimpiadas_metadata, f)

In [42]:
# Criar uma coluna de "temporada" para classificar entre Verão e inverno
olimpiadas["season"] = olimpiadas["edition"].str.extract(r'(Summer|Winter)')

verao = olimpiadas[olimpiadas["season"] == "Summer"]
inverno = olimpiadas[olimpiadas["season"] == "Winter"]

In [44]:
medalhas_verao = verao.groupby("country")[["gold", "silver", "bronze", "total"]].sum().sort_values(by=["total"], ascending=False)
print(medalhas_verao)

                              gold  silver  bronze  total
country
United States                 1110     885     786   2781
Soviet Union                   395     319     296   1010
Great Britain                  305     345     342    992
France                         247     283     307    837
Germany                        249     277     298    824
...                            ...     ...     ...    ...
Sudan                            0       1       0      1
Turkmenistan                     0       1       0      1
Tonga                            0       1       0      1
Togo                             0       0       1      1
United States Virgin Islands     0       1       0      1

[163 rows x 4 columns]

In [49]:
medalhas_verao = verao.groupby("country")[["gold", "silver", "bronze", "total"]].sum().sort_values(by=["total"], ascending=False)

medalhas_verao.to_parquet("2-gold/medalhas_olimpiadas_verao.parquet")

medalhas_verao_metadata = template.copy()

medalhas_verao_metadata["arquivo"] = "medalhas_olimpiadas_verao.parquet"
medalhas_verao_metadata["descricao"] = "dataset de medalhas de olimpiadas de verao por país"
medalhas_verao_metadata["formato"] = "parquet"
medalhas_verao_metadata["data_coleta"] = datetime.now().isoformat()
medalhas_verao_metadata["responsavel"] = "Matheus Nielsen"
medalhas_verao_metadata["colunas"] = [{
      "nome": "country",
      "tipo": "String",
      "descricao": "País participante"
    },
    {
      "nome": "gold",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro"
    },
    {
      "nome": "silver",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata"
    },
    {
      "nome": "bronze",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze"
    },
    {
      "nome": "total",
      "tipo": "Integer",
      "descricao": "Número total de medalhas"
    },
]

with open("2-gold/medalhas_olimpiadas_verao.meta.json", "w") as f:
    json.dump(medalhas_verao_metadata, f)

In [50]:
medalhas_inverno = inverno.groupby("country")[["gold", "silver", "bronze", "total"]].sum().sort_values(by=["total"], ascending=False)

medalhas_inverno.to_parquet("2-gold/medalhas_olimpiadas_inverno.parquet")

medalhas_inverno_metadata = template.copy()

medalhas_inverno_metadata["arquivo"] = "medalhas_olimpiadas_inverno.parquet"
medalhas_inverno_metadata["descricao"] = "dataset de medalhas de olimpiadas de inverno por país"
medalhas_inverno_metadata["formato"] = "parquet"
medalhas_inverno_metadata["data_coleta"] = datetime.now().isoformat()
medalhas_inverno_metadata["responsavel"] = "Matheus Nielsen"
medalhas_inverno_metadata["colunas"] = [{
      "nome": "country",
      "tipo": "String",
      "descricao": "País participante"
    },
    {
      "nome": "gold",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro"
    },
    {
      "nome": "silver",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata"
    },
    {
      "nome": "bronze",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze"
    },
    {
      "nome": "total",
      "tipo": "Integer",
      "descricao": "Número total de medalhas"
    },
]

with open("2-gold/medalhas_olimpiadas_inverno.meta.json", "w") as f:
    json.dump(medalhas_inverno_metadata, f)

In [48]:
medalhas_totais = olimpiadas.groupby("country")[["gold", "silver", "bronze", "total"]].sum().sort_values(by=["total"], ascending=False)

medalhas_totais.to_parquet("2-gold/medalhas_olimpiadas_totais.parquet")

medalhas_totais_metadata = template.copy()

medalhas_totais_metadata["arquivo"] = "medalhas_olimpiadas_totais.parquet"
medalhas_totais_metadata["descricao"] = "dataset de medalhas de olimpiadas por país"
medalhas_totais_metadata["formato"] = "parquet"
medalhas_totais_metadata["data_coleta"] = datetime.now().isoformat()
medalhas_totais_metadata["responsavel"] = "Matheus Nielsen"
medalhas_totais_metadata["colunas"] = [{
      "nome": "country",
      "tipo": "String",
      "descricao": "País participante"
    },
    {
      "nome": "gold",
      "tipo": "Integer",
      "descricao": "Número de medalhas de ouro"
    },
    {
      "nome": "silver",
      "tipo": "Integer",
      "descricao": "Número de medalhas de prata"
    },
    {
      "nome": "bronze",
      "tipo": "Integer",
      "descricao": "Número de medalhas de bronze"
    },
    {
      "nome": "total",
      "tipo": "Integer",
      "descricao": "Número total de medalhas"
    },
]

with open("2-gold/medalhas_olimpiadas_totais.meta.json", "w") as f:
    json.dump(medalhas_totais_metadata, f)